### ISSUE TITLE
[NOT A ISSUE] Add a select option for selecting a specific frame of a video 

### ISSUE THREAD

**Issue by Felzow47** [Akascape/Vdo-Img-Conversion-Tools#1]
or make a option to extract only ONE frame ! 

thx in advice !

**Comment by Akascape** [comment]
@Felzow47 Done! Added this feature of extracting a specific frame. 
(Download the new version)
**Just right click on the EXTRACT button, then select the option `Extract specific frame`.**

![](https://user-images.githubusercontent.com/89206401/227890452-766a6655-b50a-499f-abff-b9fb8e4edc3e.png)
