### ISSUE TITLE
[NOT A ISSUE] add batch extracting for all frame and specific number frame 

### ISSUE THREAD

**Issue by Felzow47** [Akascape/Vdo-Img-Conversion-Tools#2]
so already I wanted to thank you a lot
 for having been so reactive on my last request 
 and I would need one last little feature and that's AWESOME
 so i explained in my "issue" title i need a batch option for all frame and specifc number of a frame
 
 thx in advice YOU ARE FKN AWESOME

**Comment by Akascape** [comment]
@Felzow47 Means you want to extract a group of frames (in a range)?

**Comment by Akascape** [comment]
Ok, I get it.

**Comment by Akascape** [comment]
@Felzow47 Done batch import-export.
Now you can choose multiple files.
